# Site settings
# These are used to personalize your new site.
title: Edward M. Phillips # your name here
logo: "/images/profilephoto.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br /> elements if you don't need line breaks)
  CSCI 496: Senior Portfolio<br />
  In partial fulfillment of the requirements for the degree of
  Bachelor of Science in Computer-Science (class of 2023)
  <br /><br />
  <a href="https://github.com/emphillips07/emphillips07.github.io/blob/master/pdf/CompSci_Resume_final.pdf">View My Resume</a>
  <br /><br />
  <a href="https://www.linkedin.com/in/edward-phillips-0b3457210/">View My LinkedIn Profile</a>
repository: "emphillips07/emphillips07.github.io"
github_username:  emphillips07 # update with your username
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here

# Build setting
theme: jekyll-theme-minimal

